# Generated by Django 5.0.4 on 2024-11-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='users.user', verbose_name='User')),
                ('short_bio', models.TextField(blank=True, max_length=100, null=True, verbose_name='Short Biography')),
                ('facebook_account', models.URLField(blank=True, null=True, verbose_name='Facebook Account')),
                ('instagram_account', models.URLField(blank=True, null=True, verbose_name='Instagram Account')),
                ('twitter_account', models.URLField(blank=True, null=True, verbose_name='Twitter Account')),
                ('linkedin_account', models.URLField(blank=True, null=True, verbose_name='LinkedIn Account')),
                ('pinterest_account', models.URLField(blank=True, null=True, verbose_name='Pinterest Account')),
            ],
            options={
                'verbose_name': 'User Additional Information',
                'verbose_name_plural': 'Users Additional Information',
            },
        ),
    ]
