# Generated by Django 5.0.4 on 2024-11-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='facebook_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='instagram_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='linkedin_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pinterest_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='short_bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='twitter_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='users.user'),
        ),
    ]
