# Generated by Django 5.0.4 on 2024-11-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'معلومات المستخدم', 'verbose_name_plural': 'معلومات المستخدمين'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='instagram_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='linkedin_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pinterest_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='twitter_account',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='short_bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
