# Generated by Django 5.0.4 on 2024-11-24 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id_properties', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('rent', 'For rent'), ('sale', 'For sale')], default='rent', max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('daily', 'Daily rental'), ('new', 'New building')], default='apartment', max_length=20)),
                ('is_company', models.BooleanField(default=False)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=255)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('parking', models.IntegerField(default=0)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_air_condition', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_pets_allowed', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_security_cameras', models.BooleanField(default=False)),
                ('cats_allowed', models.BooleanField(default=False)),
                ('dogs_allowed', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_period', models.CharField(default='month', max_length=10)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Property Owner')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
