# Generated by Django 5.0.4 on 2024-11-25 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id_property', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('daily', 'Daily Rental'), ('new', 'New Building')], default='apartment', max_length=20)),
                ('business_type', models.CharField(choices=[('business', 'I am a registered business'), ('private', 'I am a private seller')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyContacts',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Property Contact',
                'verbose_name_plural': 'Property Contacts',
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('parking', models.IntegerField(default=0)),
                ('amenities', models.CharField(choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('security', 'Security'), ('ac', 'Air Conditioning'), ('heating', 'Heating'), ('laundry', 'Laundry'), ('elevator', 'Elevator'), ('garden', 'Garden')], default='wifi', max_length=255)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('country', models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada')], default='USA', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('main_photo', models.ImageField(upload_to='properties/main/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥')], default='USD', max_length=3)),
                ('price_period', models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], default='month', max_length=10)),
            ],
        ),
    ]
