# Generated by Django 5.0.4 on 2024-11-24 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContacts',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Property Contact',
                'verbose_name_plural': 'Property Contacts',
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('parking', models.IntegerField(default=0)),
                ('amenities', models.JSONField(default=list)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('country', models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada')], default='USA', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('main_photo', models.ImageField(upload_to='properties/main/')),
                ('additional_photos', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Property Photo',
                'verbose_name_plural': 'Property Photos',
            },
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.property')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥')], default='USD', max_length=3)),
                ('price_period', models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], default='month', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='id_properties',
            new_name='id_property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cats_allowed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dogs_allowed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_air_condition',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_gym',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_kitchen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_pets_allowed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_security_cameras',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_tv',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='property',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_period',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='property',
            name='business_type',
            field=models.CharField(choices=[('business', 'I am a registered business'), ('private', 'I am a private seller')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('daily', 'Daily Rental'), ('new', 'New Building')], default='apartment', max_length=20),
        ),
    ]
