# Generated by Django 5.0.4 on 2025-01-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pro_status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10),
        ),
    ]
