# Generated by Django 5.0.4 on 2024-11-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='amenities',
            field=models.JSONField(default=list),
        ),
    ]
