# Generated by Django 5.0.4 on 2024-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertydetails_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
    ]
