# Generated by Django 5.0.4 on 2024-11-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertydetails_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='amenities',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('security', 'Security'), ('ac', 'Air Conditioning'), ('heating', 'Heating'), ('laundry', 'Laundry'), ('elevator', 'Elevator'), ('garden', 'Garden')], default='wifi', max_length=255),
        ),
    ]
